export const progressRaw = {
  initials: {
    step: 1,
    icon: "star",
    type: "center",
    label: "ثبت مرکز",
    offset: 50,
    to: "/center/new",
  },
  legals: {
    step: 2,
    icon: "star",
    type: "center",
    label: "تکمیل اطلاعات حقوقی",
    offset: 100,
    to: "/legals/new",
  },
  legals_approval: {
    step: 3,
    type: "hl",
    offset: -20,
    to: "/",
    tooltip: "تأیید اطلاعات حقوقی",
  },
  certs: {
    step: 4,
    icon: "star",
    type: "center",
    label: "بارگزاری مجوزها",
    offset: 150,
    to: "/certs/new",
  },
  certs_approval: {
    step: 5,
    type: "hl",
    offset: -20,
    to: "/",
    tooltip: "تأیید اطلاعات مجوزها",
  },
  specialists: {
    step: 6,
    icon: "star",
    type: "center",
    label: "ثبت اطلاعات کارشناسان",
    offset: 100,
    to: "/specialists/new",
  },
  equipments: {
    step: 7,
    icon: "star",
    type: "center",
    label: "ثبت اطلاعات تجهیزات",
    offset: 50,
    to: "/equipments/new",
  },
};
