export const preSignup = [
  {
    step: 1,
    icon: "star",
    type: "center",
    label: "ثبت مرکز",
    offset: 50,
    to: "/center/new",
  },
  {
    step: 2,
    icon: "star",
    type: "center",
    label: "تکمیل اطلاعات حقوقی",
    offset: 100,
    to: "/legals/new",
  },
  {
    step: 3,
    type: "hl",
    offset: -20,
    to: "/",
    tooltip: "تأیید اطلاعات حقوقی",
  },
  {
    step: 4,
    icon: "star",
    type: "center",
    label: "بارگزاری مجوزها",
    offset: 150,
    to: "/certs/new",
  },
  {
    step: 5,
    type: "hl",
    offset: -20,
    to: "/",
    tooltip: "تأیید اطلاعات مجوزها",
  },
  {
    step: 6,
    icon: "star",
    type: "center",
    label: "ثبت اطلاعات کارشناسان",
    offset: 100,
    to: "/specialists/new",
  },
  {
    step: 7,
    icon: "star",
    type: "center",
    label: "ثبت اطلاعات تجهیزات",
    offset: 0,
    to: "/equipments/new",
  },
];
